### ISSUE TITLE
version 0.4.0 fails to detect ïï overlap on nunito/Nunito-Black.ttf

### ISSUE THREAD

**Issue by felipesanches** [simoncozens/collidoscope#7]
See https://github.com/googlefonts/fontbakery/issues/3554 and https://github.com/googlefonts/fontbakery/issues/3556 for more info.

**Comment by simoncozens** [comment]
Looks OK here. I'll take a look at the fontbakery test. Probably we are not setting the right settings.

<img width="269" alt="Screenshot 2022-01-26 at 11 00 46" src="https://user-images.githubusercontent.com/106728/151151702-814981db-fa30-4df6-9d0b-962ce3f951b1.png">

**Comment by simoncozens** [comment]
Fixed in 0.4.1 but you will need a fontbakery PR (I'll do that).
